version: "3.8"

services:
  nginx:
    # build: "./requirements/nginx"

    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - "./nginx/:/etc/nginx/templates"
    #   - ./certs:/etc/certs
    # restart: always
  mariadb:
  wordpress: