version: "3"

services:
  nginx:
    image: mynginx
    ports:
      - "443:443"
    volumes:
      - /home/login/data:/src/usr/share/nginx/html
      - /etc/nginx/ssl:/etc/nginx/ssl
    restart: always
  db:
    image: mdb
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    restart: always
  
