version: '3.5'
services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    container_name: nginx
    networks:
      - inception
    restart: always
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - 3306
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    container_name: mariadb
    networks:
      - inception
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - 9000
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    container_name: wordpress
    networks:
      - inception
    restart: always

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/$USER/data/db_data"
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      o: bind 
      type: none
      device: "/home/$USER/data/wp_data"

networks:
  inception:
    driver: bridge
