version: '3.8'
services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    container_name: nginx
    image: nginx
    networks:
      - inception
    restart: always
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    restart: always
    
  adminer:
    build: 
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mariadb
    container_name: adminer
    image: adminer
    env_file:
      - .env
    networks:
      - inception
    restart: always

  # ftp:
  #   build: 
  #     context: requirements/bonus/ftp
  #     dockerfile: Dockerfile
  #   # ports:
  #   #   - 8000:8000
  #   depends_on:
  #     - mariadb
  #   container_name: ftp
  #   image: ftp
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   restart: always

  redis:
    depends_on:
      - wordpress
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - wp_data:/var/www/html
    container_name: redis
    image: redis
    networks:
      - inception
    restart: always

  website:
    container_name: website
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    image: website
    # depends_on:
    #   - nginx
    ports:
      - 3000:3000
    restart: always
    # env_file:
    #   - .env
    networks:
      - inception

  bck_service:
    build:
      context: ./requirements/bonus/bck_service
      dockerfile: Dockerfile
    image: bck_service
    depends_on:
      - mariadb
    volumes:
      - db_data:/db_data
      - bck_data:/bck_service
    # env_file:
    #   - .env
    container_name: bck_service
    restart: always
    networks:
      - inception

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/stronk/data/db_data"
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      o: bind 
      type: none
      device: "/home/stronk/data/wp_data"
  bck_data:
    name: bck_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/stronk/data/bck_data"

networks:
  inception:
    driver: bridge
