FROM debian:buster

RUN apt-get -y update && apt-get -y upgrade &&\
	apt-get -y install curl &&\
	apt-get -y install php php7.3-mysql


COPY info.php /var/www/html/

COPY conf/www.conf /etc/php/7.3/fpm/pool.d

# COPY wp-config.php /

COPY ./script.sh /

RUN chmod 777 script.sh

ENTRYPOINT [ "./script.sh" ]

CMD [ "bash" ]
